name: Booking Check Every 5 Min

on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: 📦 Install Node dependencies (including Puppeteer)
        run: npm ci

      - name: 🔧 Install OS libraries for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libxss1 libgbm1 libgtk-3-0 libasound2t64

      - name: 📥 Download a compatible Chrome build for Puppeteer
        run: npx puppeteer browsers install chrome

      - name: 🚀 Run booking.js script
        # Script supports the following parameters:
        # --dryrun : Only check availability without making bookings
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          CI: "true"
        run: node booking.js
